Repository EdgeCrafters/ejp-be, pull requests merged in 2023-08, with the labels that each got.

#24 [fix] gitolite 세팅 수정 완료
  docker-compose.yml
  scripts/add-tutor.sh
  scripts/add-user.sh
  scripts/setup.sh
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
  thunder-tests/collections/tc_col_repo.json
  thunder-tests/collections/tc_col_rest-api.json
Labels: bug, fix

#34 [refactor] gitolite container 분리
  .devcontainer/devcontainer.json
  .gitignore
  Dockerfile
  docker-compose.yml
  scripts/add-tutor.sh
  scripts/gitolite-init.sh
  scripts/setup.sh
  src/auth/auth.controller.spec.ts
  thunder-tests/collections/tc_col_rest-api.json
  tutors.conf
Labels: refactor

#35 [refactor] repo 모듈 dto 작성
  scripts/create-new-repo.sh
  src/common/dtos/content-wrapper.dto.ts
  src/repos/dtos/addUserToRepo.dto.ts
  src/repos/dtos/createRepo.dto.ts
  src/repos/dtos/repo.dto.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
  thunder-tests/collections/tc_col_repo.json
  thunder-tests/collections/tc_col_rest-api.json
Labels: refactor

#39 [refactor] minio dockerizing 완료
  .devcontainer/devcontainer.json
  .github/ISSUE_TEMPLATE.md
  .github/pull_request_template.md
  .gitignore
  Dockerfile
  docker-compose.yml
  package.json
  pnpm-lock.yaml
  scripts/add-tutor.sh
  scripts/add-user.sh
  scripts/create-new-repo.sh
  scripts/create-user.sh
  scripts/gitolite-init.sh
  scripts/setup.sh
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/minio/minio.module.ts
  src/minio/minio.service.ts
  src/repos/dtos/createRepo.dto.ts
  src/repos/repos.service.ts
Labels: refactor

#44 [fix] testcase & hiddencase minio에 맞추어 수정
  prisma/schema.prisma
  src/submit/submit.controller.ts
  src/submit/submit.service.ts
  src/testcase/dto/testcase.dto.ts
  src/testcase/testcase.service.ts
Labels: fix

#48 getRepoInfos 메소드 구현
  prisma/seed.ts
  src/repos/repos.controller.ts
  src/repos/repos.module.ts
  src/repos/repos.service.ts
Labels: feature, fix

#50 hot-fix : creating user repo
  docker-compose.yml
  prisma/migrations/20230727042812_/migration.sql
  prisma/migrations/20230730083948_modify_testcase_table/migration.sql
  prisma/migrations/20230730084056_modify_hiddencase_table/migration.sql
  prisma/migrations/20230730130631_add_url_columns_on_testcase_and_hiddencase_table/migration.sql
  prisma/migrations/20230802044433_/migration.sql
  prisma/migrations/20230802044621_/migration.sql
  prisma/migrations/20230806062344_/migration.sql
  prisma/migrations/20230811131713_add_user_hidden_case_model/migration.sql
  prisma/migrations/20230811131938_add_is_correct_field_on_user_hidden_case/migration.sql
  prisma/migrations/20230812090919_add_output_field_on_hidden_case/migration.sql
  prisma/migrations/20230817124452_/migration.sql
  prisma/migrations/20230818063054_/migration.sql
  prisma/migrations/20230818130322_/migration.sql
  src/problem/problem.service.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
Labels: fix

#52 [fix] minio config
  .devcontainer/devcontainer.json
  docker-compose.yml
  scripts/setup.sh
  src/minio/minio.service.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
  src/testcase/testcase.service.ts
Labels: fix

#53 [feat] user 모듈 생성
  prisma/migrations/20230822153521_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/main.ts
  src/repos/repos.service.ts
  src/user/dto/add-user.dto.ts
  src/user/dto/enroll-user-repo.dto.ts
  src/user/dto/modify-user.dto.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: feature

#51 feat: add getscore service
  .devcontainer/devcontainer.json
  .eslintignore
  .github/workflows/CI.yaml
  .prettierignore
  docker-compose.yml
  scripts/setup.sh
  src/app.module.ts
  src/auth/auth.controller.ts
  src/submit/submit.controller.spec.ts
  src/submit/submit.controller.ts
  src/submit/submit.module.ts
  src/submit/submit.service.spec.ts
  src/submit/submit.service.ts
Labels: feature

#54 feat: getFile deleteFile 작성
  src/minio/minio.service.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
  src/user/user.service.spec.ts
Labels: feature

#56 fix : delete problem and repo
  src/problem/problem.controller.spec.ts
  src/problem/problem.module.ts
  src/problem/problem.service.spec.ts
  src/problem/problem.service.ts
  src/repos/repos.controller.ts
  src/repos/repos.service.ts
  src/testcase/testcase.controller.spec.ts
  src/testcase/testcase.service.spec.ts
Labels: fix

#59 fix : get score logic
  package.json
  pnpm-lock.yaml
  prisma/migrations/20230826061858_/migration.sql
  prisma/schema.prisma
  src/auth/auth.service.ts
  src/auth/class/authenticated-user.class.ts
  src/auth/serializer/local.serializer.ts
  src/auth/strategy/local.strategy.ts
  src/submit/dto/score.dto.ts
  src/submit/submit.controller.ts
  src/submit/submit.service.ts
  src/testcase/testcase.service.ts
  src/user/user.controller.ts
Labels: fix

#61 60 feat delete testcases in batch
  src/problem/problem.service.ts
  src/repos/repos.service.ts
  src/submit/submit.controller.ts
  src/submit/submit.service.ts
  src/testcase/dto/testcase.dto.ts
  src/testcase/testcase.controller.ts
  src/testcase/testcase.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feature
